apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbackend
  template:
    metadata:
      labels:
        app: testbackend
    spec:
      containers:
      - name: testbackend
        image: bakyurek/testbackend:latest
        ports:
        - containerPort: 5241
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: testbackend
  ports:
    - protocol: TCP
      port: 7211
      targetPort: 5241
  type: ClusterIP
